Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 172.16.16.0/20
  PublicSubnet1CIDR:
    Description: >-
      Please enter the IP range (CIDR notation) for the public subnet in the
      first Availability Zone
    Type: String
    Default: 172.16.17.0/22
  PublicSubnet2CIDR:
    Description: >-
      Please enter the IP range (CIDR notation) for the public subnet in the
      second Availability Zone
    Type: String
    Default: 172.16.18.0/22
  PrivateSubnet1CIDR:
    Description: >-
      Please enter the IP range (CIDR notation) for the private subnet in the
      first Availability Zone
    Type: String
    Default: 172.16.19.0/22
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Ref VpcCIDR
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName
    Metadata:
      'AWS::CloudFormation::Designer':
        id: a5c247f1-598c-494a-9f08-d1f1d542ebe6
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName
    Metadata:
      'AWS::CloudFormation::Designer':
        id: e16c6a4c-ed96-419b-8775-273a9cc4b805
  InternetGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 5f53a99c-c6b1-4819-a251-8b3071252a08
  PublicSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: us-east-1a
      CidrBlock: !Ref PublicSubnet1CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName} Public Subnet (AZ1)'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: b56eb998-7f4b-48dc-83b6-96feda6d52fa
  PublicSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select 
        - 1
        - !GetAZs ''
      CidrBlock: !Ref PublicSubnet2CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName} Public Subnet (AZ2)'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: ef432377-7bf6-402c-9045-b1861aef5313
  NatGateway1EIP:
    Type: 'AWS::EC2::EIP'
    DependsOn: InternetGatewayAttachment
    Properties:
      Domain: vpc
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 28425caa-f6c2-4313-9d76-c5d6379ee5df
  NatGateway2EIP:
    Type: 'AWS::EC2::EIP'
    DependsOn: InternetGatewayAttachment
    Properties:
      Domain: vpc
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 1a1937ba-d3b8-4cb8-a16f-bced0161dd32
  NatGateway1:
    Type: 'AWS::EC2::NatGateway'
    Properties:
      AllocationId: !GetAtt NatGateway1EIP.AllocationId
      SubnetId: !Ref PublicSubnet1
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 663dcdf5-dcb2-4c43-b01d-3923c1cf0d3d
  NatGateway2:
    Type: 'AWS::EC2::NatGateway'
    Properties:
      AllocationId: !GetAtt NatGateway2EIP.AllocationId
      SubnetId: !Ref PublicSubnet2
    Metadata:
      'AWS::CloudFormation::Designer':
        id: d84b75d2-1da8-43a9-84e9-14560a95bddf
  PublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName} Public Routes'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 4202728d-aa78-4689-a9e0-6c0f7c6b3750
  DefaultPublicRoute:
    Type: 'AWS::EC2::Route'
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 031bdfb5-d12d-43a2-b165-d8884b5297f9
  PublicSubnet1RouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 0459500d-b485-4ee4-9d18-d12f302ba4e4
  PublicSubnet2RouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet2
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 421ddcfb-27ab-449a-a3d4-d816dc1fde85
  NoIngressSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: no-ingress-sg
      GroupDescription: Security group with no ingress rule
      VpcId: !Ref VPC
    Metadata:
      'AWS::CloudFormation::Designer':
        id: d7cb6d42-8add-45d1-ad82-72315ad027f2
  WebServerGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      AvailabilityZones: !GetAZs ''
      LaunchConfigurationName: !Ref LaunchConfig
      MinSize: '2'
      MaxSize: '2'
      LoadBalancerNames:
        - !Ref ElasticLoadBalancer
      NotificationConfiguration:
        TopicARN: !Ref NotificationTopic
        NotificationTypes:
          - 'autoscaling:EC2_INSTANCE_LAUNCH'
          - 'autoscaling:EC2_INSTANCE_LAUNCH_ERROR'
          - 'autoscaling:EC2_INSTANCE_TERMINATE'
          - 'autoscaling:EC2_INSTANCE_TERMINATE_ERROR'
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M
        Count: '1'
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: '1'
        MaxBatchSize: '1'
    Properties:
      KeyName: !Ref KeyName
      ImageId: !FindInMap 
        - AWSRegionArch2AMI
        - !Ref 'AWS::Region'
        - !FindInMap 
          - AWSInstanceType2Arch
          - !Ref InstanceType
          - Arch
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      InstanceType: !Ref InstanceType


 ElasticLoadBalancer:
  Type: AWS::ElasticLoadBalancing::LoadBalancer
  Properties:
    AvailabilityZones:
      Fn::GetAZs: ''
    Instances:
    - Ref: Ec2Instance1
    - Ref: Ec2Instance2
    Listeners:
    - LoadBalancerPort: '8080'
      Protocol: HTTP
    HealthCheck:
      Target:
        Fn::Join:
        - ''
        - - 'HTTP:'
          - Ref: WebServerPort
          - "/"

Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: !Ref VPC
  PublicSubnets:
    Description: A list of the public subnets
    Value: !Join 
      - ','
      - - !Ref PublicSubnet1
        - !Ref PublicSubnet2
  PrivateSubnets:
    Description: A list of the private subnets
    Value: !Join 
      - ','
      - - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
  PublicSubnet1:
    Description: A reference to the public subnet in the 1st Availability Zone
    Value: !Ref PublicSubnet1
  PublicSubnet2:
    Description: A reference to the public subnet in the 2nd Availability Zone
    Value: !Ref PublicSubnet2
  PrivateSubnet1:
    Description: A reference to the private subnet in the 1st Availability Zone
    Value: !Ref PrivateSubnet1
  PrivateSubnet2:
    Description: A reference to the private subnet in the 2nd Availability Zone
    Value: !Ref PrivateSubnet2
  NoIngressSecurityGroup:
    Description: Security group with no ingress rule
    Value: !Ref NoIngressSecurityGroup
Metadata:
  'AWS::CloudFormation::Designer':
    e16c6a4c-ed96-419b-8775-273a9cc4b805:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 1020
      z: 1
      embeds: []
    a5c247f1-598c-494a-9f08-d1f1d542ebe6:
      size:
        width: 960
        height: 870
      position:
        x: -100
        'y': -500
      z: 1
      embeds:
        - d7cb6d42-8add-45d1-ad82-72315ad027f2
        - 4202728d-aa78-4689-a9e0-6c0f7c6b3750
        - ef432377-7bf6-402c-9045-b1861aef5313
        - b56eb998-7f4b-48dc-83b6-96feda6d52fa
    d7cb6d42-8add-45d1-ad82-72315ad027f2:
      size:
        width: 60
        height: 60
      position:
        x: -70
        'y': 160
      z: 2
      parent: a5c247f1-598c-494a-9f08-d1f1d542ebe6
      embeds: []
      iscontainedinside:
        - a5c247f1-598c-494a-9f08-d1f1d542ebe6
        - a5c247f1-598c-494a-9f08-d1f1d542ebe6
        - a5c247f1-598c-494a-9f08-d1f1d542ebe6
        - a5c247f1-598c-494a-9f08-d1f1d542ebe6
    4202728d-aa78-4689-a9e0-6c0f7c6b3750:
      size:
        width: 240
        height: 240
      position:
        x: -70
        'y': -140
      z: 2
      parent: a5c247f1-598c-494a-9f08-d1f1d542ebe6
      embeds:
        - 031bdfb5-d12d-43a2-b165-d8884b5297f9
        - 2e299ea3-a088-478f-82ac-d4fc1a5009ed
      iscontainedinside:
        - a5c247f1-598c-494a-9f08-d1f1d542ebe6
        - a5c247f1-598c-494a-9f08-d1f1d542ebe6
        - a5c247f1-598c-494a-9f08-d1f1d542ebe6
        - a5c247f1-598c-494a-9f08-d1f1d542ebe6
    ef432377-7bf6-402c-9045-b1861aef5313:
      size:
        width: 240
        height: 240
      position:
        x: 220
        'y': -450
      z: 2
      parent: a5c247f1-598c-494a-9f08-d1f1d542ebe6
      embeds:
        - d84b75d2-1da8-43a9-84e9-14560a95bddf
      iscontainedinside:
        - a5c247f1-598c-494a-9f08-d1f1d542ebe6
        - a5c247f1-598c-494a-9f08-d1f1d542ebe6
        - a5c247f1-598c-494a-9f08-d1f1d542ebe6
        - a5c247f1-598c-494a-9f08-d1f1d542ebe6
    421ddcfb-27ab-449a-a3d4-d816dc1fde85:
      source:
        id: 4202728d-aa78-4689-a9e0-6c0f7c6b3750
      target:
        id: ef432377-7bf6-402c-9045-b1861aef5313
      z: 2
    b56eb998-7f4b-48dc-83b6-96feda6d52fa:
      size:
        width: 240
        height: 250
      position:
        x: -70
        'y': -450
      z: 2
      parent: a5c247f1-598c-494a-9f08-d1f1d542ebe6
      embeds:
        - 663dcdf5-dcb2-4c43-b01d-3923c1cf0d3d
      iscontainedinside:
        - a5c247f1-598c-494a-9f08-d1f1d542ebe6
        - a5c247f1-598c-494a-9f08-d1f1d542ebe6
        - a5c247f1-598c-494a-9f08-d1f1d542ebe6
        - a5c247f1-598c-494a-9f08-d1f1d542ebe6
    0459500d-b485-4ee4-9d18-d12f302ba4e4:
      source:
        id: 4202728d-aa78-4689-a9e0-6c0f7c6b3750
      target:
        id: b56eb998-7f4b-48dc-83b6-96feda6d52fa
      z: 2
    5f53a99c-c6b1-4819-a251-8b3071252a08:
      source:
        id: a5c247f1-598c-494a-9f08-d1f1d542ebe6
      target:
        id: e16c6a4c-ed96-419b-8775-273a9cc4b805
      z: 1
    031bdfb5-d12d-43a2-b165-d8884b5297f9:
      size:
        width: 60
        height: 60
      position:
        x: -40
        'y': -80
      z: 3
      parent: 4202728d-aa78-4689-a9e0-6c0f7c6b3750
      embeds: []
      isassociatedwith:
        - e16c6a4c-ed96-419b-8775-273a9cc4b805
      iscontainedinside:
        - 4202728d-aa78-4689-a9e0-6c0f7c6b3750
        - 4202728d-aa78-4689-a9e0-6c0f7c6b3750
        - 4202728d-aa78-4689-a9e0-6c0f7c6b3750
        - 4202728d-aa78-4689-a9e0-6c0f7c6b3750
      dependson:
        - 5f53a99c-c6b1-4819-a251-8b3071252a08
    1a1937ba-d3b8-4cb8-a16f-bced0161dd32:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 1020
      z: 1
      embeds: []
      dependson:
        - 5f53a99c-c6b1-4819-a251-8b3071252a08
    d84b75d2-1da8-43a9-84e9-14560a95bddf:
      size:
        width: 60
        height: 60
      position:
        x: 250
        'y': -390
      z: 3
      parent: ef432377-7bf6-402c-9045-b1861aef5313
      embeds: []
      iscontainedinside:
        - ef432377-7bf6-402c-9045-b1861aef5313
        - ef432377-7bf6-402c-9045-b1861aef5313
        - ef432377-7bf6-402c-9045-b1861aef5313
        - ef432377-7bf6-402c-9045-b1861aef5313
    28425caa-f6c2-4313-9d76-c5d6379ee5df:
      size:
        width: 60
        height: 60
      position:
        x: 300
        'y': 1020
      z: 1
      embeds: []
      dependson:
        - 5f53a99c-c6b1-4819-a251-8b3071252a08
    663dcdf5-dcb2-4c43-b01d-3923c1cf0d3d:
      size:
        width: 60
        height: 60
      position:
        x: -40
        'y': -380
      z: 3
      parent: b56eb998-7f4b-48dc-83b6-96feda6d52fa
      embeds: []
      iscontainedinside:
        - b56eb998-7f4b-48dc-83b6-96feda6d52fa
        - b56eb998-7f4b-48dc-83b6-96feda6d52fa
        - b56eb998-7f4b-48dc-83b6-96feda6d52fa
        - b56eb998-7f4b-48dc-83b6-96feda6d52fa
    2e299ea3-a088-478f-82ac-d4fc1a5009ed:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': -120
      z: 3
      parent: 4202728d-aa78-4689-a9e0-6c0f7c6b3750
      embeds: []
